// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // Use same config as Android for desktop
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAx5wLgbFxuf4aKlp887QqxyK8cWdEc0bY',
    appId: '1:421764703984:android:a9c4f0e9faaa7d54718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDqpR84cWovAfHuQYkhzQxxh8PuOFqNg',
    appId: '1:421764703984:web:fa76413e5b81ef9f718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    authDomain: 'quotebot-vision-hackathon.firebaseapp.com',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5wLgbFxuf4aKlp887QqxyK8cWdEc0bY',
    appId: '1:421764703984:android:a9c4f0e9faaa7d54718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9fSnNbwoS7qH8qSrK4IacMsIbx3pk7s',
    appId: '1:421764703984:ios:a621b88cf2ebd0f0718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
    iosBundleId: 'com.quotebot.quotebotVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9fSnNbwoS7qH8qSrK4IacMsIbx3pk7s',
    appId: '1:421764703984:ios:a621b88cf2ebd0f0718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
    iosBundleId: 'com.quotebot.quotebotVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDqpR84cWovAfHuQYkhzQxxh8PuOFqNg',
    appId: '1:421764703984:web:7488fdab2ec89da6718435',
    messagingSenderId: '421764703984',
    projectId: 'quotebot-vision-hackathon',
    authDomain: 'quotebot-vision-hackathon.firebaseapp.com',
    storageBucket: 'quotebot-vision-hackathon.firebasestorage.app',
  );
}
