name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.x' # Puedes cambiarlo según tu versión exacta
          
      - name: Install Dependencies
        working-directory: ./app
        run: flutter pub get
        
      - name: Build Web App (HTML Renderer)
        working-directory: ./app
        run: flutter build web --web-renderer html --no-tree-shake-icons
        
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
